/*
 Quantcast measurement tag
 Copyright (c) 2008-2022, Quantcast Corp.
*/
'use strict';(function(d,u,r){var v=function(a){var b=r.createElement("a");b.href=a;return b},w=[/^http[s]?:\/\/((adservice.google.*)|([^\/]*fls\.doubleclick\.net))\/.*~oref=(?<url>[^;\n]*)/,/^http[s]?:\/\/[^\/]*tealium.*\/.*page_url=(?<url>[^&]*)/],x=function(){if(u.top!==u.self){try{for(var a=0;a<w.length;a++){var b=r.location.href.match(w[a]);if(b&&b.groups.url){var e=decodeURIComponent(b.groups.url);break}}}catch(c){}return e?v(e):v(r.referrer)}return r.location},y=function(a){return a.replace(/^[\s\uFEFF\xA0]+|[\s\uFEFF\xA0]+$/g,
"")},z=function(a){return{}.toString.call(a).match(/\s([a-zA-Z]+)/)[1].toLowerCase()},A=function(a,b,e){return a?"nc"===a?!b||!e||0>b.indexOf(e):"eq"===a?b===e:"sw"===a?0===b.indexOf(e):"ew"===a?(a=b.length-e.length,b=b.lastIndexOf(e,a),-1!==b&&b===a):"c"===a?0<=b.indexOf(e):!1:!1},f=function(a,b,e){var c=x().hostname;A(b,c,e)?a(c):a(!1)},l=function(a,b,e){var c=x().href;A(b,c,e)?a(c):a(!1)},p=function(a,b,e){b=document.getElementsByTagName("meta");for(var c,m,k=[],t=0;t<b.length;t++)if(c=b[t],m=
c.getAttribute("name")||c.getAttribute("property"),m==e){m=k;k=m.concat;var h=e;if(c=c.getAttribute("content")){var n=h;n=-1!==n.toLowerCase().indexOf("tag")||-1!==n.toLowerCase().indexOf("keyword")||0===n.toLowerCase().indexOf("qc:");-1===h.toLowerCase().indexOf("tag")&&-1===h.toLowerCase().indexOf("keyword")&&0===h.toLowerCase().indexOf("qc:")||(c=c.replace(/\.+/g," "));if(n)for(h=c.split(","),c=0;c<h.length;c++)h[c]=y(h[c]);else h=y(c.replace(/,+/g," "))}else h=c;k=k.call(m,h)}0<k.length?a(k):
a(!1)},g=function(a){return"array"===z(a)?{labels:a.join(",")}:{labels:""+a}},q=function(a,b){var e=[],c;if("array"===z(b)){for(c=0;c<b.length;c++)e.push(a+"."+b[c]);return{labels:e.join(",")}}return{labels:a+"."+b}};__qc.apply(null,["rules",[d,null,[[q,"Allure.Keywords"]],[[p,"exactmatch","keywords"],[l,"c","allure.com"]]],[d,null,[[q,"Allure.Author"]],[[p,"exactmatch","author"],[l,"c","allure.com"]]],[d,null,[[q,"Allure.Type"]],[[p,"exactmatch","og:type"],[l,"c","allure.com"]]],[d,null,[[q,"Allure.Title"]],
[[p,"exactmatch","og:title"],[l,"c","allure.com"]]],[d,null,[[g,"Allure.Makeup Looks.Face"]],[[f,"c","allure.com/makeup-looks/face"]]],[d,null,[[g,"Allure.Makeup Looks.Nail Ideas"]],[[f,"c","allure.com/makeup-looks/nail-ideas"]]],[d,null,[[g,"Allure.Skin Care"]],[[f,"c","allure.com/skin-care"]]],[d,null,[[g,"Allure.Makeup Looks"]],[[f,"c","allure.com/makeup-looks"]]],[d,null,[[g,"Allure.Fragrance"]],[[f,"c","allure.com/perfume"]]],[d,null,[[g,"Allure.Skin Care.Anti Aging"]],[[f,"c","allure.com/skin-care/anti-aging-skin"]]],
[d,null,[[g,"Allure.Makeup Looks.Eyes"]],[[f,"c","allure.com/makeup-looks/eyes"]]],[d,null,[[g,"Allure.Makeup Looks.Lips"]],[[f,"c","allure.com/makeup-looks/lips"]]],[d,null,[[g,"Allure.Skin Care.Acne"]],[[f,"c","allure.com/skin-care/acne"]]],[d,null,[[g,"Allure.Hair Ideas"]],[[f,"c","allure.com/hair-ideas"]]],[d,null,[[g,"Allure.Hair Ideas.Cuts"]],[[f,"c","allure.com/hair-ideas/cuts"]]],[d,null,[[g,"Allure.Hair Ideas.Styles"]],[[f,"c","allure.com/hair-ideas/styles"]]],[d,null,[[g,"Allure.Fashion"]],
[[f,"c","allure.com/shopping"]]],[d,null,[[g,"Allure.Fashion.Red Carpet Style"]],[[f,"c","allure.com/shopping/red-carpet"]]],[d,null,[[g,"Allure.Fashion.Red Carpet Style.Kendall Jenner's Met Gala Dress Was Made From A Single Piece of String"]],[[f,"c","www.allure.com/story/kendall-jenner-la-perla-met-gala-2017-gown"]]],[d,null,[[g,"Allure.Shopping.Street Style"]],[[f,"c","allure.com/shopping/street-style"]]],[d,null,[[g,"Allure.Fashion.Trends"]],[[f,"c","allure.com/shopping/fashion-trends"]]],[d,
null,[[g,"Allure.Hair Ideas.Color"]],[[f,"c","allure.com/hair-ideas/color"]]],[d,null,[[g,"Allure.Fashion.Red Carpet Style.Oscars 2017 All the Fashion Looks From the Red Carpet"]],[[f,"c","allure.com/gallery/best-dressed-celebrities-oscars-2017"]]],[d,null,[[g,"Allure.Fashion.Red Carpet Style.Jennifer Lopez Channels Elsa at the 2017 Met Gala"]],[[f,"c","allure.com/story/jennifer-lopez-disney-princess-met-gala"]]],[d,null,[[q,"Allure.News Keywords"]],[[p,"exactmatch","news_keywords"],[l,"c","allure.com"]]]])})("p-Jjy-Cyr1NZGRz",
window,document);